### PR TITLE
Add snap packaging (classic)

### PR DESCRIPTION
**Pull request by farshidtz**
How to use:
- build
- install
- run add-addon-service and connect-snap-interfaces scripts
- configure
- snap start or sudo snap run

To run with debuggin:
```
sudo WRITABLE_LOGLEVEL=DEBUG snap run edgex-device-ft232h-bme680.device-ft232h-bme680
```

### CODE REVIEW

**Comment by MonicaisHer** [comment]
```
level=INFO source=variables.go:352 msg="Variables override of 'Driver.PythonPath' by environment variable: DRIVER_PYTHONPATH=/snap/edgex-device-ft232h-bme680/x1/bin/python"
level=INFO ts=2022-09-01T07:03:38.226315879Z app=device-ft232h-bme680 source=config.go:283 msg="Loaded custom configuration from file (2 envVars overrides applied)"
...
level=ERROR source=init.go:57 msg="Failed to init ProtocolDriver: unable to get python version: fork/exec /snap/edgex-device-ft232h-bme680/x1/bin/python: no such file or directory: "
```
```
$ which python
/usr/bin/python
```
I have update the Driver.PythonPath="/usr/bin/python", but it has been overwritten by snapcraft. Do you have any idea how should I configure this snap to work with my python?

**Comment by farshidtz** [comment]
The python is packaged in the snap. The error seems to be related to python scripts not being found.

Could you show the output of `tree /snap/edgex-device-ft232h-bme680/current/bin`?

**Comment by farshidtz** [comment]
I could not reproduce your issue. Here is what I did:
```
snap remove --purge edgex-device-ft232h-bme680 
snapcraft clean
snapcraft -v
snap install ./edgex-device-ft232h-bme680_0+git.af8b6dd-dirty_amd64.snap --dangerous --classic
./add-addon-service.sh 
./connect-snap-interfaces.sh 
snap start edgex-device-ft232h-bme680.device-ft232h-bme680 
```
```
$ snap logs -f edgex-device-ft232h-bme680.device-ft232h-bme680 
...
2022-09-01T11:04:29+02:00 edgex-device-ft232h-bme680.device-ft232h-bme680[44439]: level=INFO ts=2022-09-01T09:04:29.352293222Z app=device-ft232h-bme680 source=message.go:55 msg="device service started"
2022-09-01T11:04:29+02:00 edgex-device-ft232h-bme680.device-ft232h-bme680[44439]: level=INFO ts=2022-09-01T09:04:29.35229734Z app=device-ft232h-bme680 source=message.go:58 msg="Service started in: 9.771266ms"
```

**Comment by MonicaisHer** [comment]
> snap start edgex-device-ft232h-bme680.device-ft232h-bme680

The difference between your script and mine is `sudo snap`

**Comment by farshidtz** [comment]
> The difference between your script and mine is `snap` and `sudo snap`. Can you reproduce it with `sudo snap`?

Same. I used Ubuntu 22.04. 

Looking at the error again, it is the `python` bin that isn't found at `/snap/edgex-device-ft232h-bme680/x1/bin/python`.

**Comment by MonicaisHer** [comment]
```
$ tree /snap/edgex-device-ft232h-bme680/x1/bin/
/snap/edgex-device-ft232h-bme680/x1/bin/
├── activate
├── activate.csh
├── activate.fish
├── Activate.ps1
├── device-ft232h-bme680
├── ft232h-bme680.py
├── ft232h-gpio.py
├── ftconf.py
├── ftdi_urls.py
├── i2cscan.py
├── pip
├── pip3
├── pip3.10
├── __pycache__
│   ├── ftconf.cpython-310.pyc
│   ├── ftdi_urls.cpython-310.pyc
│   ├── i2cscan.cpython-310.pyc
│   └── pyterm.cpython-310.pyc
├── pyserial-miniterm
├── pyserial-ports
├── pyterm.py
├── python -> python3 <---------------------------(red broken link)
├── python3 -> /usr/bin/python3.10 <--------------(red broken link)
└── python3.10 -> python3 <-----------------------(red broken link)
```

**Comment by MonicaisHer** [comment]
Symbolic link works:
```
sudo ln -sf /bin/python3.8 /usr/bin/python3.10
```
There is a `adafruit_bme680` error:
```
msg="device service started"
msg="Service started in: 6.986262ms"
msg="AutoEvent - error occurs when reading resource ReadAll: error reading DeviceCommand ReadAll for GasSensor -> exit status 1: Traceback (most recent call last):\n  File \"ft232h-bme680.py\", line 1, in <module>\n    import adafruit_bme680\nModuleNotFoundError: No module named 'adafruit_bme680'\n"
```

**Comment by farshidtz** [comment]
Thanks for your review @MonicaisHer. I have created an issue to address this later.

**Pull request merged**
